In [1]:
import numpy as np
import pandas as pd

In [2]:
arr_1 = np.array([[0, 1, 2, 3, 4, 5],
                  [10, 11, 12, 13, 14, 15]])

In [3]:
arr_1

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [4]:
arr_2 = np.array([[19, 20, 21, 22, 23, 24],
                  [25, 26, 27, 28, 29, 30]])

In [5]:
arr_2

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [6]:
#1. How to concatenate two numpy arrays column-wise and row-wise?
np.concatenate((arr_1,arr_2),axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [7]:
np.concatenate((arr_1,arr_2),axis=1)

array([[ 0,  1,  2,  3,  4,  5, 19, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 15, 25, 26, 27, 28, 29, 30]])

In [8]:
#2.Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

array=np.random.rand(5)
array

array([0.08448321, 0.03396023, 0.44701479, 0.87908649, 0.02224332])

In [9]:
#3.Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10
a = np.random.randint(5, 10, size = (5,3,2))
a

array([[[8, 8],
        [9, 7],
        [5, 9]],

       [[7, 7],
        [6, 9],
        [6, 6]],

       [[7, 9],
        [7, 6],
        [7, 8]],

       [[5, 9],
        [9, 7],
        [7, 7]],

       [[9, 7],
        [6, 6],
        [7, 8]]])

In [10]:
#4.Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and randint() from random library.
import random

In [11]:
def random_array(num):
    rand_num=random.sample(range(1,50),num)
    return rand_num
random_array(random.randint(1,10))

[30, 22, 23, 21, 35]

In [12]:
#5. Create and Compute median using both Naive method using python only and Numpy function np.median()
import statistics
arr=[6,25,23,43,11,60]
print("median:%s"%(statistics.median(arr)))

median:24.0


In [35]:
arr=[6,25,23,43,11,60]
np.median(arr)

24.0

In [38]:
arr2 = [6,25,23,43,11,60]
l = len(arr2)
arr2.sort()
  
if l % 2 == 0:
    md1 = arr2[l//2]
    md2 = arr2[l//2 - 1]
    median = (md1 + md2)/2
else:
    median = arr2[l//2]
print("Median is: " + str(median))

Median is: 24.0


In [13]:
#6.Create naive function to compute variance function, mean function using only python.
arr_3=[11,14,10,21,18,43,35]
variance_1=statistics.variance(arr_3)
variance_1

159.23809523809524

In [14]:
mean_1=statistics.mean(arr_3)
mean_1

21.714285714285715

In [15]:
#7.Convert a 1D array to a 2D array with 2 rows
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr2=np.reshape(arr,(2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
#8.How to stack two arrays vertically? Stack arrays A and B vertically?
A=np.array([2,3,4,5,6])
B=np.array([7,8,9,10,11])
C=np.vstack((A,B))
C

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [17]:
#9.Create a function using numpy to get the common items between two python numpy arrays?
arr_4=np.array([3,2,4,6,8])
arr_5=np.array([5,9,2,8,7])
common=np.intersect1d(arr_4,arr_5)
common

array([2, 8])

In [18]:
#10.Create a python function to get the positions where elements of two arrays match using Numpy function?
arr_4=np.array([3,8,4,2,9])
arr_5=np.array([5,8,7,2,1])

a=(np.where(arr_4==arr_5))
a   

(array([1, 3], dtype=int64),)

In [19]:
#11.How to create a 2D array containing random floats between 5 and 10?
arr_6=np.random.uniform(5,10, size=(2,2))
arr_6

array([[8.11243935, 7.13290757],
       [5.64053695, 7.63820212]])

In [20]:
#12.Extract the text column species from the 1D iris imported using following url np.genfromtxt()
import pandas as pd
iris_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv", sep=',', 
                        header = 0)
iris_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [21]:
data=iris_df[['species']]
data.head(10)

species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa
5  setosa
6  setosa
7  setosa
8  setosa
9  setosa

In [22]:
#13.How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?
iris_1=iris_df.copy()
iris_1.drop(index=[0],columns=['species'],inplace=True)
iris_1d=np.array(iris_1)
iris_2d=iris_1d.reshape(149,4)
iris_2d

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3

In [23]:
#14.How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?
iris_df.agg(['mean','median','std'])

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.057333      3.758000     1.199333
median      5.800000     3.000000      4.350000     1.300000
std         0.828066     0.435866      1.765298     0.762238

In [24]:
admission_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv", sep=',', 
                        header = 0)
admission_df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [25]:
#15.How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
admission_1=admission_df.values
def Normalize(data):
    return(data-np.min(data))/(np.max(data))-(np.min(data))
scale=Normalize(admission_1)
scale

array([[0.002  , 0.674  , 0.236  , ..., 0.0193 , 0.002  , 0.00184],
       [0.004  , 0.648  , 0.214  , ..., 0.01774, 0.002  , 0.00152],
       [0.006  , 0.632  , 0.208  , ..., 0.016  , 0.002  , 0.00144],
       ...,
       [0.996  , 0.66   , 0.24   , ..., 0.01912, 0.002  , 0.00186],
       [0.998  , 0.624  , 0.206  , ..., 0.01686, 0.     , 0.00146],
       [1.     , 0.654  , 0.226  , ..., 0.01808, 0.     , 0.00168]])

In [26]:
#16.Compute and Find the number and position of missing values in iris data’s sepal length column.
iris_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [27]:
#17.Drop rows that contain a missing value from a numpy array created by using iris dataset? 
iris_df.dropna()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
#18.Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for both.
admission_df['TOEFL Score'].sort_values()

368     92
28      93
79      93
411     94
347     94
      ... 
81     120
97     120
297    120
143    120
497    120
Name: TOEFL Score, Length: 500, dtype: int64

In [29]:
admission_df['GRE Score'].sort_values()

377    290
117    290
168    293
79     294
272    294
      ... 
81     340
84     340
143    340
384    340
429    340
Name: GRE Score, Length: 500, dtype: int64

In [41]:
#19.Compute the Euclidean distance between two arrays using Numpy linalg?


In [31]:
#20.Compute and Find the duplicate entries in the given Numpy array and mark them as True. Create 1-D array 
a=np.array([2,3,4,5,6,7,3,5])
uniques=np.unique(a)
result=[]
for i in a:
    if i not in uniques:
        result.append(True)
    else:
        result.append(False)
        uniques=np.delete(uniques,np.where(uniques==i))
print('Array: ',a)
result

Array:  [2 3 4 5 6 7 3 5]


[False, False, False, False, False, False, True, True]

In [32]:
#21.How to replace all missing values with 0, in a numpy array using Admission.csv and iris.csv?
a=admission_df.isnull().replace("0")
a


Serial No.  GRE Score  TOEFL Score  University Rating    SOP   LOR   \
0         False      False        False              False  False  False   
1         False      False        False              False  False  False   
2         False      False        False              False  False  False   
3         False      False        False              False  False  False   
4         False      False        False              False  False  False   
..          ...        ...          ...                ...    ...    ...   
495       False      False        False              False  False  False   
496       False      False        False              False  False  False   
497       False      False        False              False  False  False   
498       False      False        False              False  False  False   
499       False      False        False              False  False  False   

      CGPA  Research  Chance of Admit   
0    False     False             False  
1    False     False             False  
2    False     False             False  
3    False     False             False  
4    False     False             False  
..     ...       ...               ...  
495  False     False             False  
496  False     False             False  
497  False     False             False  
498  False     False             False  
499  False     False             False  

[500 rows x 9 columns]